version: '3.8'


services:

  redis:
    image: redis:latest
    container_name: cb_redis
    volumes:
      - redis-data:/data

  bot:

    build:
      context: .
    env_file:
      - .env
    container_name: cb_bot
    depends_on:
      - redis

volumes:
  - redis-data:
      driver: local


